[build]
  command = "npm install && npx vite build"
  publish = "dist/public"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
