[build]
  command = "npm ci --legacy-peer-deps && npx vite build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_BASE_URL = "https://fivetelite-talent.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
